### ISSUE TITLE
Sample Project

### ISSUE THREAD

**Issue by ghost** [donwibier/DXWeb#2]
Hi Don,

Would it be possible to get a sample project that demonstrates the use of your XPO ASPNET Identity nuget package?

**Comment by egarim** [comment]
yes  sample project would be nice, I download the source but the project did not work when I changed the connection string to use sql server

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DX.Utils.Conversion.<>c.<GetConfigOption>b__11_2(String[] t) in C:\Users\Joche\Documents\Visual Studio 2017\Projects\Test\TestIdentity\DX.Utils\Conversion.cs:line 283
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at DX.Utils.Conversion.GetConfigOption(String configString, String configOption, String& result) in C:\Users\Joche\Documents\Visual Studio 2017\Projects\Test\TestIdentity\DX.Utils\Conversion.cs:line 281
   at DX.Utils.Conversion.GetConfigOption[TEnum](String configString, String configOption, TEnum defaultValue) in C:\Users\Joche\Documents\Visual Studio 2017\Projects\Test\TestIdentity\DX.Utils\Conversion.cs:line 297
   at DX.Data.Xpo.XpoDatabase.createDataLayer(String connectionString, String datalayerName) in C:\Users\Joche\Documents\Visual Studio 2017\Projects\Test\TestIdentity\DX.Data.Xpo\XpoDatabase.cs:line 150
   at DX.Data.Xpo.XpoDatabase.GetDataLayer(String connectionString, String dataLayerName) in C:\Users\Joche\Documents\Visual Studio 2017\Projects\Test\TestIdentity\DX.Data.Xpo\XpoDatabase.cs:line 125
   at DX.Data.Xpo.XpoDatabase..ctor(String connectionString, String connectionName) in C:\Users\Joche\Documents\Visual Studio 2017\Projects\Test\TestIdentity\DX.Data.Xpo\XpoDatabase.cs:line 69
   at DX.Data.Xpo.XpoCoreExtensions.AddXpoDatabase(IServiceCollection serviceCollection, String connectionName, String connectionString) in C:\Users\Joche\Documents\Visual Studio 2017\Projects\Test\TestIdentity\DX.Data.Xpo\XpoCoreExtensions.cs:line 18
   at DX.Test.Web.Core.Startup.ConfigureServices(IServiceCollection services) in C:\Users\Joche\Documents\Visual Studio 2017\Projects\Test\TestIdentity\DX.Test.Web.Core\Startup.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

**Comment by donwibier** [comment]
Hi, Sorry for the late response, but the repo now includes a .NET core as well as a .NET Framework MVC sample project

**Comment by ghost** [comment]
Thanks @donwibier

**Comment by bajwaimran** [comment]
I am using Dx.Data.Xpo.Identity package and I am trying to create a role manager class so that I can add roles and map the roles with user. But i am unable to do that because i am not able to find proper documetation on this.



using DX.Data.Xpo.Identity;

public class ApplicationRoleManager : RoleManager<XPIdentityRole, int>
    {
        public ApplicationRoleManager(IRoleStore<CustomRole, int> roleStore)
            : base(roleStore)
        {
        }


        public static ApplicationRoleManager Create(IdentityFactoryOptions<ApplicationRoleManager> options, IOwinContext context)
        {
            return new ApplicationRoleManager(new RoleStore<CustomRole, int, CustomUserRole>(context.Get<ApplicationDbContext>()));
        }
    }


This is basic class which is working find with Entity Framework but with XPO identity i am not able to create one.
Please suggest what changes i have to made in order to make this class working.

**Comment by donwibier** [comment]
First, sorry for the delay in responding :-o

The configuration is slightly different as with EF Identity.
Please take a good look at: https://github.com/donwibier/DXWeb/blob/master/README.md and let me know if there are any issues.
